name = "Keep Vanilla"
author = "cesarcamiloig"
version = "0.2.0"
description = "Modpack de máxima optimización y estabilidad para Minecraft 26.2 en Fabric. Rendimiento superior y control visual total sin alterar las mecánicas Vanilla del juego."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22e21a2504786f62ace41bc73a4733e7ac258ae7f200da5f7eb69b04fd86cccf"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
