name = "Keep Vanilla"
author = "cesarcamiloig"
version = "1.0.0"
description = "Minecraft Vanilla optimizado, estable y eficiente, con mejoras de calidad de vida cuidadosamente seleccionadas para preservar la esencia original del juego."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cf25768b70c38ca2fd824a616ff4819603b60232d2979a41b086d9c270ffc57"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
