name = "Keep Vanilla"
author = "cesarcamiloig"
version = "1.0.0"
description = "Minecraft Vanilla optimizado, estable y eficiente, con mejoras de calidad de vida cuidadosamente seleccionadas para preservar la esencia original del juego."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ca2fe91db37b3fad03bb102564e288e0bf01f3395372dd1b9c0265e1111f503"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
